spring:
  application:
    name: gateway
 
server:
  port: 8866
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
zuul:
  routes:
    order:
      path: /order/**
      #超时配置说明：
      #如果路由方式是serviceId的方式，配置为：zuul:routes:order:serviceId，那么ribbon的超时配置生效（order-service:ribbon:ReadTimeout）
      #如果如果是url的方式，配置为：zuul:routes:order:url，则zuul.host开头的超时生效。
      serviceId: order-service
      #url: http://localhost:8763
    user:
      path: /user/**
      serviceId: user-service
    msg:
      path: /msg/**
      serviceId: msg-service
    statis:
      path: /statis/**
      serviceId: statis-service
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
 
order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
 

