#配置中心参考：https://www.jianshu.com/p/41c2cd7c498a
server:
  port: 8866

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8861/eureka/

spring:
  application:
    name: cn-config-server
   #连接到sleuth-zipkin链路追踪
  zipkin:
    #zipkin不能注册到eureka中，所以这里只能硬编码url
    base-url: http://localhost:8865
  sleuth:
    sampler:
        #这个是收集比例，1表示100%shouji ,全部收集
        percentage: 1
  cloud:
    config:
      server:
        git:
          #这是其他项目配置文件的git仓库地址
          uri: https://github.com/notMyPen/demo-config
          #配置文件目录
          #searchPaths: '{application}'
          #label: master
          #github账号
          username: notMyPen
          #github密码
          password: 9cqb8nyc
          basedir:  E:/WorkFile/config/local/cnuo

security:
  basic:
    enabled: true
  user:
    #这是config-server的用户名和密码
    name: config
    password: 123456
